//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcStore
    {
        public int ID { get; set; }
        public Nullable<int> FirstNumber { get; set; }
        public Nullable<int> SecondNumber { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Answer { get; set; }
    }
}
